# A Universal Prompt for Feature Discovery

In [1]:
import os
import requests
import time
import datetime
import json
import threading
import pandas as pd

## Prompt

The prompt assumes the following metadata is provided:

* Dataset Name
* Description
* Target and its values
* Example of random forty rows

In [3]:
from string import Template

prompt_template = Template("""
{
    "system_message": "IMPORTANT: Return only a valid JSON object with no explanations, text, or markdown!!! Do not include any commentary or introductory text!!!",
    "input_metadata": {
        "dataset_name": "$name",
        "description": "$description",
        "target": "$target",
        "examples": "$examples"
    },
    "task": {
        "steps": [
            "Analyze the provided metadata and examples to determine the domain and context of the dataset.",
            "Identify the key characteristics of the dataset relevant to predicting the target variable.",
            "List potential high-level categorical and numerical features based on domain knowledge inferred from the dataset description.",
            "Extract additional potential features from dataset examples using syntactic and semantic patterns, ensuring at least 20 distinct features are generated.",
            "If the text implies certain values that match the target, these values may also be extracted as features. In cases where the target has multiple values, each value can be independently derived from the text as a feature if it is contextually appropriate.",
            "For text-based datasets, identify key phrases, structural components, and linguistic patterns that are relevant.",
            "For numerical datasets, identify aggregation patterns, distributional characteristics, and possible transformations.",
            "Group related features into meaningful categories where applicable.",
            "If a feature has more than 15 unique categories, group less frequent categories into an 'Other' class.",
            "For each identified feature, provide a clear name, description, a complete list of possible values, and a specific LLM extraction query."
        ],
        "constraints": [
            "Ensure features are distinct and non-redundant.",
            "Note that the target variable is not explicitly present in the input text.",
            "Prioritize domain-specific insights over generic ones.",
            "Ensure output is a structured, valid JSON format.",
            "For categorical variables, list possible values with domain justification.",
            "For numeric variables, provide possible transformations (e.g., log, mean differences).",
            "The extraction queries must be specific and detailed to ensure high-quality feature generation.",
            "Tailor extraction queries to the domain context of the dataset.",
            "Generate a diverse set of features to maximize potential predictive power."
        ]
    },
    "output_format": {
        "type": "json",
        "structure": {
            "features": [
                {
                    "feature_name": "<Name of the categorical or numerical feature>",
                    "description": "<Short description of what the feature represents and how it relates to the dataset's context>",
                    "possible_values": ["<Value 1>", "<Value 2>", "...", "<Value n>"],
                    "extraction_query": "Identify the '<feature_name>' based on the provided context. Options: '<Value 1>', '<Value 2>', ..., '<Value n>'."
                }
            ]
        }
    }
}
""")

In [4]:
# Generate prompt
def generate_prompt(name, description, target, examples_df, text, target_col):
    # 40 random rows
    random_examples = examples_df[[text, target_col]].sample(n=40, random_state=42).to_dict(orient='records')
    examples = '\n'.join([str(row) for row in random_examples])
    
    return prompt_template.substitute(name=name, description=description, target=target, examples=examples)

## Datasets

### C19

In [ ]:
c19_dataset = pd.read_csv("c19_final.csv")[['abstract', 'cited']]
c19_dataset

### M17

In [ ]:
m17_dataset = pd.read_csv("m17_final.csv")[['abstract', 'evaluation']]
m17_dataset

### Hate

In [5]:
# https://paperswithcode.com/dataset/hate-speech
from datasets import load_dataset

dataset = load_dataset("odegiber/hate_speech18")
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'user_id', 'subforum_id', 'num_contexts', 'label'],
        num_rows: 10944
    })
})

In [6]:
import pandas as pd
hate_dataset = pd.DataFrame(dataset['train'])
hate_dataset

,text,user_id,subforum_id,num_contexts,label
0,"As of March 13th , 2014 , the booklet had been...",572066,1346,0,0
1,In order to help increase the booklets downloa...,572066,1346,0,0
2,( Simply copy and paste the following text int...,572066,1346,0,0
3,Click below for a FREE download of a colorfull...,572066,1346,0,1
4,Click on the `` DOWNLOAD ( 7.42 MB ) '' green ...,572066,1346,0,0
...,...,...,...,...,...
10939,"Billy - `` That guy would n't leave me alone ,...",734541,1388,0,0
10940,Wish we at least had a Marine Le Pen to vote f...,735154,1388,0,0
10941,Its like the choices are white genocide candid...,735154,1388,0,0
10942,Why White people used to say that sex was a si...,572266,1388,0,1
10943,Now I get it !,572266,1388,0,0

### BANKING77

In [7]:
# https://paperswithcode.com/dataset/banking77-oos
from datasets import load_dataset

data = load_dataset("banking77")
data

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 10003
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 3080
    })
})

In [8]:
import pandas as pd
bank_dataset = pd.DataFrame(data['train'])
bank_dataset

                                                    text  label
0                         I am still waiting on my card?     11
1      What can I do if my card still hasn't arrived ...     11
2      I have been waiting over a week. Is the card s...     11
3      Can I track my card while it is in the process...     11
4      How do I know if I will get my card, or if it ...     11
...                                                  ...    ...
9998              You provide support in what countries?     24
9999                  What countries are you supporting?     24
10000                What countries are getting support?     24
10001                     Are cards available in the EU?     24
10002                   Which countries are represented?     24

[10003 rows x 2 columns]

In [9]:
bank_dataset_test = pd.DataFrame(data['test'])
bank_dataset_test

                                                   text  label
0                              How do I locate my card?     11
1     I still have not received my new card, I order...     11
2     I ordered a card but it has not arrived. Help ...     11
3      Is there a way to know when my card will arrive?     11
4                          My card has not arrived yet.     11
...                                                 ...    ...
3075      If i'm not in the UK, can I still get a card?     24
3076                 How many countries do you support?     24
3077              What countries do you do business in?     24
3078             What are the countries you operate in.     24
3079         Can the card be mailed and used in Europe?     24

[3080 rows x 2 columns]

In [10]:
bank_dataset = pd.concat([bank_dataset, bank_dataset_test], axis=0)

## List of All Datasets with Description

In [15]:
datasets = [
        {
        'df': c19_dataset,
        'prefix': 'c19',
        'name': 'CORD-19 scientific articles',
        'description': 'Scientific articles from multiple disciplines and a target being a proxy for research impact.',
        'text_column': 'abstract',
        'target_column': 'cited',
        'target': 'cited (0/1). Target is a binary variable - with 1 representing works cited more than the median value adjusted in time, 0 represents articles with lower or equal to the median citation count.',
        },
        {
        'df': m17_dataset,
        'prefix': 'm17',
        'name': 'M17+ scientific articles',
        'description': 'Scientific articles from multiple disciplines and a target being a proxy for research impact.',
        'text_column': 'abstract',
        'target_column': 'evaluation',
        'target': 'evaluation 1 to 5. Target is an ordinal variable of human evaluation of the quality of articles, 1 indicates works of world-class quality, 5 means mediocre articles of low importance and impact.',
        },
        {
        'df': bank_dataset,
        'prefix': 'bank77',
        'name': 'BANKING77 dataset',
        'description': 'BANKING77 dataset provides a very fine-grained set of intents in a banking domain. It comprises 13,083 customer service queries labeled with 77 intents. It focuses on fine-grained single-domain intent detection.',
        'text_column': 'text',
        'target_column': 'label',
        'target': """
                   "label": datasets.features.ClassLabel(
                    names=[
                        "activate_my_card",
                        "age_limit",
                        "apple_pay_or_google_pay",
                        "atm_support",
                        "automatic_top_up",
                        "balance_not_updated_after_bank_transfer",
                        "balance_not_updated_after_cheque_or_cash_deposit",
                        "beneficiary_not_allowed",
                        "cancel_transfer",
                        "card_about_to_expire",
                        "card_acceptance",
                        "card_arrival",
                        "card_delivery_estimate",
                        "card_linking",
                        "card_not_working",
                        "card_payment_fee_charged",
                        "card_payment_not_recognised",
                        "card_payment_wrong_exchange_rate",
                        "card_swallowed",
                        "cash_withdrawal_charge",
                        "cash_withdrawal_not_recognised",
                        "change_pin",
                        "compromised_card",
                        "contactless_not_working",
                        "country_support",
                        "declined_card_payment",
                        "declined_cash_withdrawal",
                        "declined_transfer",
                        "direct_debit_payment_not_recognised",
                        "disposable_card_limits",
                        "edit_personal_details",
                        "exchange_charge",
                        "exchange_rate",
                        "exchange_via_app",
                        "extra_charge_on_statement",
                        "failed_transfer",
                        "fiat_currency_support",
                        "get_disposable_virtual_card",
                        "get_physical_card",
                        "getting_spare_card",
                        "getting_virtual_card",
                        "lost_or_stolen_card",
                        "lost_or_stolen_phone",
                        "order_physical_card",
                        "passcode_forgotten",
                        "pending_card_payment",
                        "pending_cash_withdrawal",
                        "pending_top_up",
                        "pending_transfer",
                        "pin_blocked",
                        "receiving_money",
                        "Refund_not_showing_up",
                        "request_refund",
                        "reverted_card_payment?",
                        "supported_cards_and_currencies",
                        "terminate_account",
                        "top_up_by_bank_transfer_charge",
                        "top_up_by_card_charge",
                        "top_up_by_cash_or_cheque",
                        "top_up_failed",
                        "top_up_limits",
                        "top_up_reverted",
                        "topping_up_by_card",
                        "transaction_charged_twice",
                        "transfer_fee_charged",
                        "transfer_into_account",
                        "transfer_not_received_by_recipient",
                        "transfer_timing",
                        "unable_to_verify_identity",
                        "verify_my_identity",
                        "verify_source_of_funds",
                        "verify_top_up",
                        "virtual_card_not_working",
                        "visa_or_mastercard",
                        "why_verify_identity",
                        "wrong_amount_of_cash_received",
                        "wrong_exchange_rate_for_cash_withdrawal",
                    ]        
""",  
    },
    {
        'df': hate_dataset,
        'prefix': 'hate',
        'name': 'Hate Speech',
        'description': 'Dataset of hate speech annotated on Internet forum posts in English at sentence-level. The source forum in Stormfront, a large online community of white nacionalists. A total of 10,568 sentence have been been extracted from Stormfront and classified as conveying hate speech or not.',
        'text_column': 'text',
        'target_column': 'label',
        'target': 'label (0/1), 1 is hate, 0 is noHate',  
    },
]

## LLM-based Feature Discovery

In [16]:
from langchain_openai import ChatOpenAI

# Inicializace ChatGPT
llm = ChatOpenAI(
    model_name="gpt-4o-2024-08-06", 
    temperature=0,
    max_tokens=4096,
    top_p=0.9,  # Omezuje pravděpodobnostní prostor odpovědí
    frequency_penalty=0,  # Minimalizuje variabilitu ve výstupech
    presence_penalty=0,  # Zajišťuje, že odpovědi nebudou příliš rozmanité
    api_key="<key>"
)

response = llm.invoke('Who are you?')
response.content

'I am an AI language model created by OpenAI, designed to assist with a wide range of questions and tasks by providing information and generating text based on the input I receive. How can I assist you today?'

In [17]:
prompts = {}
for i, dataset in enumerate(datasets):
    response = llm.invoke(generate_prompt(dataset['name'], dataset['description'], dataset['target'], dataset['df'], dataset['text_column'], dataset['target_column']))
    prompts[i] = response.content
# prompts

In [18]:
import re
import json

def extract_json(response: str):
    # Find JSON between ```json and ```
    match = re.search(r"```json\s*(.*?)\s*```", response, re.DOTALL)
    if match:
        json_str = match.group(1)
        try:
            return json.loads(json_str)
        except json.JSONDecodeError as e:
            raise ValueError(f"Chyba při dekódování JSON: {e}")
    else:
        return json.loads(response.strip('```json').strip('```'))

import json
def clean_json_output(response_dict):
    cleaned_dict = {}
    for key, value in response_dict.items():
        value = extract_json(value)
        cleaned_dict[key] = value
    return cleaned_dict

In [19]:
# Remove markdown
clean_response = clean_json_output(prompts)

clean_response

{0: {'features': [{'feature_name': 'intent_category',
    'description': 'The specific intent category of the customer query within the banking domain.',
    'possible_values': ['activate_my_card',
     'age_limit',
     'apple_pay_or_google_pay',
     'atm_support',
     'automatic_top_up',
     'balance_not_updated_after_bank_transfer',
     'balance_not_updated_after_cheque_or_cash_deposit',
     'beneficiary_not_allowed',
     'cancel_transfer',
     'card_about_to_expire',
     'card_acceptance',
     'card_arrival',
     'card_delivery_estimate',
     'card_linking',
     'card_not_working',
     'card_payment_fee_charged',
     'card_payment_not_recognised',
     'card_payment_wrong_exchange_rate',
     'card_swallowed',
     'cash_withdrawal_charge',
     'cash_withdrawal_not_recognised',
     'change_pin',
     'compromised_card',
     'contactless_not_working',
     'country_support',
     'declined_card_payment',
     'declined_cash_withdrawal',
     'declined_transfer',
     'direct_debit_payment_not_recognised',
     'disposable_card_limits',
     'edit_personal_details',
     'exchange_charge',
     'exchange_rate',
     'exchange_via_app',
     'extra_charge_on_statement',
     'failed_transfer',
     'fiat_currency_support',
     'get_disposable_virtual_card',
     'get_physical_card',
     'getting_spare_card',
     'getting_virtual_card',
     'lost_or_stolen_card',
     'lost_or_stolen_phone',
     'order_physical_card',
     'passcode_forgotten',
     'pending_card_payment',
     'pending_cash_withdrawal',
     'pending_top_up',
     'pending_transfer',
     'pin_blocked',
     'receiving_money',
     'Refund_not_showing_up',
     'request_refund',
     'reverted_card_payment?',
     'supported_cards_and_currencies',
     'terminate_account',
     'top_up_by_bank_transfer_charge',
     'top_up_by_card_charge',
     'top_up_by_cash_or_cheque',
     'top_up_failed',
     'top_up_limits',
     'top_up_reverted',
     'topping_up_by_card',
     'transaction_charged_twice',
     'transfer_fee_charged',
     'transfer_into_account',
     'transfer_not_received_by_recipient',
     'transfer_timing',
     'unable_to_verify_identity',
     'verify_my_identity',
     'verify_source_of_funds',
     'verify_top_up',
     'virtual_card_not_working',
     'visa_or_mastercard',
     'why_verify_identity',
     'wrong_amount_of_cash_received',
     'wrong_exchange_rate_for_cash_withdrawal'],
    'extraction_query': "Identify the 'intent_category' based on the provided context. Options: 'activate_my_card', 'age_limit', 'apple_pay_or_google_pay', ..., 'wrong_exchange_rate_for_cash_withdrawal'."},
   {'feature_name': 'query_length',
    'description': 'The length of the customer query in terms of the number of words.',
    'possible_values': ['short', 'medium', 'long'],
    'extraction_query': "Determine the 'query_length' based on the number of words in the query. Options: 'short', 'medium', 'long'."},
   {'feature_name': 'contains_question',
    'description': 'Indicates whether the customer query contains a question.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_question'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_currency',
    'description': 'Indicates whether the customer query mentions a currency.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_currency'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_card_reference',
    'description': 'Indicates whether the customer query mentions a card.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_card_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_transfer_reference',
    'description': 'Indicates whether the customer query mentions a transfer.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_transfer_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_security_reference',
    'description': 'Indicates whether the customer query mentions security or fraud.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_security_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_fee_reference',
    'description': 'Indicates whether the customer query mentions fees or charges.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_fee_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_time_reference',
    'description': 'Indicates whether the customer query mentions time or duration.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_time_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_verification_reference',
    'description': 'Indicates whether the customer query mentions verification.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_verification_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_limit_reference',
    'description': 'Indicates whether the customer query mentions limits or restrictions.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_limit_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_support_reference',
    'description': 'Indicates whether the customer query mentions support or assistance.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_support_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_payment_reference',
    'description': 'Indicates whether the customer query mentions payments.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_payment_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_withdrawal_reference',
    'description': 'Indicates whether the customer query mentions withdrawals.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_withdrawal_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_refund_reference',
    'description': 'Indicates whether the customer query mentions refunds.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_refund_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_app_reference',
    'description': 'Indicates whether the customer query mentions the app or application.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_app_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_account_reference',
    'description': 'Indicates whether the customer query mentions an account.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_account_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_exchange_reference',
    'description': 'Indicates whether the customer query mentions exchange rates or currency exchange.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_exchange_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_top_up_reference',
    'description': 'Indicates whether the customer query mentions top-up or recharging.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_top_up_reference'. Options: 'yes', 'no'."},
   {'feature_name': 'contains_device_reference',
    'description': 'Indicates whether the customer query mentions a device such as a phone or card reader.',
    'possible_values': ['yes', 'no'],
    'extraction_query': "Identify if the query 'contains_device_reference'. Options: 'yes', 'no'."}]},
 1: {'features': [{'feature_name': 'Presence of Racial Slurs',
    'description': 'Indicates whether the text contains racial slurs or derogatory terms related to race.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Racial Slurs' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Mention of Ethnic Groups',
    'description': 'Identifies if specific ethnic groups are mentioned in the text.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Mention of Ethnic Groups' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Aggressive Language',
    'description': 'Determines if the text uses aggressive or violent language.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Aggressive Language' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Sentiment Polarity',
    'description': 'Measures the overall sentiment of the text, whether positive, negative, or neutral.',
    'possible_values': ['Positive', 'Negative', 'Neutral'],
    'extraction_query': "Identify the 'Sentiment Polarity' based on the provided context. Options: 'Positive', 'Negative', 'Neutral'."},
   {'feature_name': 'Use of First Person Pronouns',
    'description': 'Indicates the presence of first-person pronouns, suggesting personal involvement or opinion.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of First Person Pronouns' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Second Person Pronouns',
    'description': 'Indicates the presence of second-person pronouns, suggesting direct address to another individual or group.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Second Person Pronouns' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Third Person Pronouns',
    'description': 'Indicates the presence of third-person pronouns, suggesting discussion about others.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Third Person Pronouns' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Presence of Question Marks',
    'description': 'Indicates whether the text contains questions, which may imply inquiry or challenge.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Question Marks' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Presence of Exclamation Marks',
    'description': 'Indicates whether the text contains exclamation marks, suggesting emphasis or strong emotion.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Exclamation Marks' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Length of Text',
    'description': 'Measures the length of the text in terms of word count.',
    'possible_values': ['Short', 'Medium', 'Long'],
    'extraction_query': "Identify the 'Length of Text' based on the provided context. Options: 'Short', 'Medium', 'Long'."},
   {'feature_name': 'Presence of Hate Speech Keywords',
    'description': 'Indicates whether the text contains keywords commonly associated with hate speech.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Hate Speech Keywords' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Sarcasm',
    'description': 'Determines if the text uses sarcasm, which can alter the perceived meaning of statements.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Sarcasm' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Hyperbole',
    'description': 'Indicates the use of exaggerated statements or claims not meant to be taken literally.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Hyperbole' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Presence of Personal Attacks',
    'description': 'Indicates whether the text contains personal attacks or insults directed at individuals.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Personal Attacks' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Historical References',
    'description': 'Determines if the text includes references to historical events or figures.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Historical References' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Religious References',
    'description': 'Indicates whether the text contains references to religious beliefs or figures.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Religious References' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Political References',
    'description': 'Determines if the text includes references to political ideologies or figures.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Political References' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Humor',
    'description': 'Indicates whether the text uses humor, which can affect the interpretation of the content.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Humor' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Metaphors',
    'description': 'Determines if the text uses metaphors, which can convey complex ideas through analogy.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Metaphors' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Idioms',
    'description': 'Indicates whether the text contains idiomatic expressions, which can add cultural context.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Idioms' based on the provided context. Options: 'Yes', 'No'."}]},
 2: {'features': [{'feature_name': 'News Source Credibility',
    'description': 'Indicates whether the news source is generally considered credible or not.',
    'possible_values': ['Credible', 'Not Credible'],
    'extraction_query': "Identify the 'News Source Credibility' based on the provided context. Options: 'Credible', 'Not Credible'."},
   {'feature_name': 'Political Bias',
    'description': 'Represents the political bias of the news article, if any.',
    'possible_values': ['Left', 'Right', 'Neutral'],
    'extraction_query': "Identify the 'Political Bias' based on the provided context. Options: 'Left', 'Right', 'Neutral'."},
   {'feature_name': 'Presence of Hyperbolic Language',
    'description': 'Indicates whether the article uses exaggerated or hyperbolic language.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Hyperbolic Language' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Emotional Appeal',
    'description': 'Indicates whether the article uses emotional appeal to influence readers.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Emotional Appeal' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Article Length',
    'description': 'The length of the article in terms of word count.',
    'possible_values': ['Short', 'Medium', 'Long'],
    'extraction_query': "Identify the 'Article Length' based on the provided context. Options: 'Short', 'Medium', 'Long'."},
   {'feature_name': 'Presence of Expert Opinion',
    'description': 'Indicates whether the article includes opinions from experts.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Expert Opinion' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Statistical Data',
    'description': 'Indicates whether the article uses statistical data to support claims.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Statistical Data' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Presence of Direct Quotes',
    'description': 'Indicates whether the article includes direct quotes from individuals.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Direct Quotes' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Subject Matter',
    'description': 'The primary subject matter of the article.',
    'possible_values': ['Politics',
     'Economy',
     'Health',
     'Technology',
     'World News',
     'Other'],
    'extraction_query': "Identify the 'Subject Matter' based on the provided context. Options: 'Politics', 'Economy', 'Health', 'Technology', 'World News', 'Other'."},
   {'feature_name': 'Tone of the Article',
    'description': 'The overall tone of the article.',
    'possible_values': ['Positive', 'Negative', 'Neutral'],
    'extraction_query': "Identify the 'Tone of the Article' based on the provided context. Options: 'Positive', 'Negative', 'Neutral'."},
   {'feature_name': 'Presence of Visual Media',
    'description': 'Indicates whether the article includes visual media such as images or videos.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Visual Media' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': "Author's Reputation",
    'description': 'The reputation of the author in terms of credibility and reliability.',
    'possible_values': ['High', 'Medium', 'Low'],
    'extraction_query': "Identify the 'Author's Reputation' based on the provided context. Options: 'High', 'Medium', 'Low'."},
   {'feature_name': 'Date of Publication',
    'description': 'The recency of the article based on its publication date.',
    'possible_values': ['Recent', 'Old'],
    'extraction_query': "Identify the 'Date of Publication' based on the provided context. Options: 'Recent', 'Old'."},
   {'feature_name': 'Presence of Correction or Retraction',
    'description': 'Indicates whether the article has been corrected or retracted.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Correction or Retraction' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Level of Detail',
    'description': 'The level of detail provided in the article.',
    'possible_values': ['High', 'Medium', 'Low'],
    'extraction_query': "Identify the 'Level of Detail' based on the provided context. Options: 'High', 'Medium', 'Low'."},
   {'feature_name': 'Presence of Logical Fallacies',
    'description': 'Indicates whether the article contains logical fallacies.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Logical Fallacies' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Use of Sensational Headlines',
    'description': 'Indicates whether the article uses sensational headlines to attract readers.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Use of Sensational Headlines' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Presence of Multiple Perspectives',
    'description': 'Indicates whether the article presents multiple perspectives on the issue.',
    'possible_values': ['Yes', 'No'],
    'extraction_query': "Identify the 'Presence of Multiple Perspectives' based on the provided context. Options: 'Yes', 'No'."},
   {'feature_name': 'Target Audience',
    'description': 'The intended audience for the article.',
    'possible_values': ['General Public', 'Specialized Audience'],

## Feature Generation Prompt

In [20]:
def generate_feature_queries(features, text):
    queries = {
        "input_text": text,
        "task": "Extract the following features as described below and return a valid JSON object.",
        "constraints": [
            "The output must be a valid JSON.",
            "All answers must be simple and correspond to categorical values only."
        ],
        "features": [
            {
                "feature_name": feature['feature_name'],
                "description": feature['description'],
                "extraction_query": feature['extraction_query'].replace('{text}', text)
            } for feature in features['features']
        ],
        "output_format": {
            "type": "json",
            "structure": {
                "features": [
                    {
                        "feature_name": "<Feature Name>",
                        "answer": "<Extracted Answer>"
                    }
                ]
            }
        }
    }
    return json.dumps(queries)

### Feature Generation with Batch API

In [21]:
# Create a JSONL file for the Batch API
def create_batch_file(df, text_column, file, features):
    if os.path.exists(file):
        print(f"The file '{file}' already exists.")
        return file
    with open(file, "w", encoding="utf-8") as f:
        for rid, row in df.iterrows():
            text = row[text_column]
            query = generate_feature_queries(features, text)
    
            request_data = {
                "custom_id": f"{rid}", # Unique ID for each request
                "method": "POST",
                "url": "/v1/chat/completions", # Endpoint that the Batch API will process
                "body": {
                    "model": "gpt-4o-mini-2024-07-18", # Or another supported model
                    "temperature": 0,
                    "max_tokens": 4096,
                    "top_p": 0.9,  # Restricts the probability space of responses
                    "frequency_penalty": 0,  # Minimizes output variability
                    "presence_penalty": 0,  
                    "messages": [
                        {"role": "system", "content": "You are an expert in extracting categorical features from text. IMPORTANT: Return only a valid JSON object with no aditional explanations, text, or markdown. Do not use triple backticks, and do not include any commentary or introductory text."},
                        {"role": "user", "content": query}
                    ]
                }
            }
            # Zapsat každou žádost na jeden řádek JSONL
            f.write(json.dumps(request_data, ensure_ascii=False) + "\n")
    print("\nBatch created.")
    print(f"Generated .jsonl contains {len(df)} requests.")
    return file

In [22]:
for i, dataset in enumerate(datasets):
    df = dataset['df']
    text_column = dataset['text_column']
    file = "input_" + dataset['prefix'] + "_batch.jsonl"
    features = clean_response[i]
    batch_file = create_batch_file(df, text_column, file, features)
    dataset['batch_file'] = batch_file
datasets

The file 'input_bank77_batch.jsonl' already exists.
The file 'input_hate_batch.jsonl' already exists.
The file 'input_fake_batch.jsonl' already exists.
The file 'input_math_batch.jsonl' already exists.
The file 'input_bank_batch.jsonl' already exists.

[{'df':                                                    text  label
  0                        I am still waiting on my card?     11
  1     What can I do if my card still hasn't arrived ...     11
  2     I have been waiting over a week. Is the card s...     11
  3     Can I track my card while it is in the process...     11
  4     How do I know if I will get my card, or if it ...     11
  ...                                                 ...    ...
  3075      If i'm not in the UK, can I still get a card?     24
  3076                 How many countries do you support?     24
  3077              What countries do you do business in?     24
  3078             What are the countries you operate in.     24
  3079         Can the card be mailed and used in Europe?     24

  [13083 rows x 2 columns],
  'prefix': 'bank77',
  'name': 'BANKING77 dataset',
  'description': 'BANKING77 dataset provides a very fine-grained set of intents in a banking domain. It comprises 13,083 customer service queries labeled with 77 intents. It focuses on fine-grained single-domain intent detection.',
  'text_column': 'text',
  'target_column': 'label',
  'target': '\n                   "label": datasets.features.ClassLabel(\n                    names=[\n                        "activate_my_card",\n                        "age_limit",\n                        "apple_pay_or_google_pay",\n                        "atm_support",\n                        "automatic_top_up",\n                        "balance_not_updated_after_bank_transfer",\n                        "balance_not_updated_after_cheque_or_cash_deposit",\n                        "beneficiary_not_allowed",\n                        "cancel_transfer",\n                        "card_about_to_expire",\n                        "card_acceptance",\n                        "card_arrival",\n                        "card_delivery_estimate",\n                        "card_linking",\n                        "card_not_working",\n                        "card_payment_fee_charged",\n                        "card_payment_not_recognised",\n                        "card_payment_wrong_exchange_rate",\n                        "card_swallowed",\n                        "cash_withdrawal_charge",\n                        "cash_withdrawal_not_recognised",\n                        "change_pin",\n                        "compromised_card",\n                        "contactless_not_working",\n                        "country_support",\n                        "declined_card_payment",\n                        "declined_cash_withdrawal",\n                        "declined_transfer",\n                        "direct_debit_payment_not_recognised",\n                        "disposable_card_limits",\n                        "edit_personal_details",\n                        "exchange_charge",\n                        "exchange_rate",\n                        "exchange_via_app",\n                        "extra_charge_on_statement",\n                        "failed_transfer",\n                        "fiat_currency_support",\n                        "get_disposable_virtual_card",\n                        "get_physical_card",\n                        "getting_spare_card",\n                        "getting_virtual_card",\n                        "lost_or_stolen_card",\n                        "lost_or_stolen_phone",\n                        "order_physical_card",\n                        "passcode_forgotten",\n                        "pending_card_payment",\n                        "pending_cash_withdrawal",\n                        "pending_top_up",\n                        "pending_transfer",\n                        "pin_blocked",\n                        "receiving_money",\n                        "Refund_not_showing_up",\n                        "request_refund",\n                        "reverted_card_payment?",\n                        "supported_cards_and_currencies",\n                        "terminate_account",\n                        "top_up_by_bank_transfer_charge",\n                        "top_up_by_card_charge",\n                        "top_up_by_cash_or_cheque",\n                        "top_up_failed",\n                        "top_up_limits",\n                        "top_up_reverted",\n                        "topping_up_by_card",\n                        "transaction_charged_twice",\n                        "transfer_fee_charged",\n                        "transfer_into_account",\n                        "transfer_not_received_by_recipient",\n                        "transfer_timing",\n                        "unable_to_verify_identity",\n                        "verify_my_identity",\n                        "verify_source_of_funds",\n                        "verify_top_up",\n                        "virtual_card_not_working",\n                        "visa_or_mastercard",\n                        "why_verify_identity",\n                        "wrong_amount_of_cash_received",\n                        "wrong_exchange_rate_for_cash_withdrawal",\n                    ]        \n',
  'batch_file': 'input_bank77_batch.jsonl'},
 {'df':                                                     text  user_id  \
  0      As of March 13th , 2014 , the booklet had been...   572066
  1      In order to help increase the booklets downloa...   572066
  2      ( Simply copy and paste the following text int...   572066
  3      Click below for a FREE download of a colorfull...   572066
  4      Click on the `` DOWNLOAD ( 7.42 MB ) '' green ...   572066
  ...                                                  ...      ...
  10939  Billy - `` That guy would n't leave me alone ,...   734541
  10940  Wish we at least had a Marine Le Pen to vote f...   735154
  10941  Its like the choices are white genocide candid...   735154
  10942  Why White people used to say that sex was a si...   572266
  10943                                     Now I get it !   572266

         subforum_id  num_contexts  label
  0             1346             0      0
  1             1346             0      0
  2             1346             0      0
  3             1346             0      1
  4             1346             0      0
  ...            ...           ...    ...
  10939         1388             0      0
  10940         1388             0      0
  10941         1388             0      0
  10942         1388             0      1
  10943         1388             0      0

  [10944 rows x 5 columns],
  'prefix': 'hate',
  'name': 'Hate Speech',
  'description': 'Dataset of hate speech annotated on Internet forum posts in English at sentence-level. The source forum in Stormfront, a large online community of white nacionalists. A total of 10,568 sentence have been been extracted from Stormfront and classified as conveying hate speech or not.',
  'text_column': 'text',
  'target_column': 'label',
  'target': 'label (0/1), 1 is hate, 0 is noHate',
  'batch_file': 'input_hate_batch.jsonl'},
 {'df':                                                 Combined Fake
  0      Title:  Donald Trump Sends Out Embarrassing Ne...  Yes
  1      Title:  Drunk Bragging Trump Staffer Started R...  Yes
  2      Title:  Sheriff David Clarke Becomes An Intern...  Yes
  3      Title:  Trump Is So Obsessed He Even Has Obama...  Yes
  4      Title:  Pope Francis Just Called Out Donald Tr...  Yes
  ...                                                  ...  ...
  44893  Title: 'Fully committed' NATO backs new U.S. a...   No
  44894  Title: LexisNexis withdrew two products from C...   No
  44895  Title: Minsk cultural hub becomes haven from a...   No
  44896  Title: Vatican upbeat on possibility of Pope F...   No
  44897  Title: Indonesia to buy $1.14 billion worth of...   No

  [44898 rows x 2 columns],
  'prefix': 'fake',
  'name': 'Fake News Detection',
  'description': 'Fake news detection is a process that involves analyzing news content to determine its truthfulness. The news is classified as real or fake.',
  'text_column': 'Combined',
  'target_column': 'Fake',
  'target': 'Fake (Yes/No)',
  'batch_file': 'input_fake_batch.jsonl'},
 {'df':                                     Question with answer chosen
  0      Question: I was reading up on the Fibonacci Se...    Yes
  1      Question: I was reading up on the Fibonacci Se...     No
  2      Question: Given the semi-major axis and a flat...    Yes
  3      Question: Given the semi-major axis and a flat...     No
  4      Question: Given two points  $p_1$  ,  $p_2$  a...    Yes
  ...                                                  ...    ...
  37447  Question: I'm stuck with this problem: Calcula...     No
  37448  Question: I'm familiar with the  steady-state ...    Yes
  37449  Question: I'm familiar with the  steady-state ...     No
  37450  Question: Question: Losses follow an exponenti...    Yes
  37451  Question: Question: Losses follow an exponenti...     No

  [37452 rows x 2 columns],
  'prefix': 'math',
  'name': 'HuggingFace H4 Stack Exchange Preference Dataset',
  'description': 'The preference dataset is derived from the math.stackexchange.com. Each instance represents a question related to mathematics and the answer, which, if it was good, is chosen. Only the answer is important for the feature extraction.',
  'text_column': 'Question with answer',
  'target_column': 'chosen',
  'target': 'chosen (Yes/No)',
  'batch_file': 'input_math_batch.jsonl'},
 {'df':                                                    text  label
  0                        I am still waiting on my card?     11
  1     What can I do if my card still hasn't arrived ...     11
  2     I have been waiting over a week. Is the card s...     11
  3     Can I track my card while it is in the process...     11
  4     How do I know if I will get my card, or if it ...     11
  ...                                                 ...    ...
  3075      If i'm not in the UK, can I still get a card?     24
  3076                 How many countries do you support?     24
  3077              What countries do you do business in?     24
  3078             What are the countries you operate in.     24
  3079         Can the card be mailed and used in Europe?     24

  [13083 rows x 2 columns],
  'prefix': 'bank',
  'name': 'BANKING77 dataset',
  'description': 'BANKING77 dataset provides a very fine-grained set of intents in a banking domain. It comprises 13,083 customer service queries labeled with 77 intents. It focuses on fine-grained single-domain intent detection.',
  'text_column': 'text',
  'target_column': 'label',
  'target': '\n                   "label": datasets.features.ClassLabel(\n                    names=[\n                        "activate_my_card",\n                        "age_limit",\n                        "apple_pay_or_google_pay",\n                        "atm_support",\n                        "automatic_top_up",\n                        "balance_not_updated_after_bank_transfer",\n                        "balance_not_updated_after_cheque_or_cash_deposit",\n                        "beneficiary_not_allowed",\n                        "cancel_transfer",\n                        "card_about_to_expire",\n                        "card_acceptance",\n                        "card_arrival",\n                        "card_delivery_estimate",\n                        "card_linking",\n                        "card_not_working",\n                        "card_payment_fee_charged",\n                        "card_payment_not_recognised",\n                        "card_payment_wrong_exchange_rate",\n                        "card_swallowed",\n                        "cash_withdrawal_charge",\n                        "cash_withdrawal_not_recognised",\n                        "change_pin",\n                        "compromised_card",\n                        "contactless_not_working",\n                        "country_support",\n                        "declined_card_payment",\n                        "declined_cash_withdrawal",\n                        "declined_transfer",\n                        "direct_debit_payment_not_recognised",\n                        "disposable_card_limits",\n                        "edit_personal_details",\n                        "exchange_charge",\n                        "exchange_rate",\n                        "exchange_via_app",\n                        "extra_charge_on_statement",\n                        "failed_transfer",\n                        "fiat_currency_support",\n                        "get_disposable_virtual_card",\n                        "get_physical_card",\n                        "getting_spare_card",\n                        "getting_virtual_card",\n                        "lost_or_stolen_card",\n                        "lost_or_stolen_phone",\n                        "order_physical_card",\n                        "passcode_forgotten",\n                        "pending_card_payment",\n                        "pending_cash_withdrawal",\n                        "pending_top_up",\n                        "pending_transfer",\n                        "pin_blocked",\n                        "receiving_money",\n                        "Refund_not_showing_up",\n                        "request_refund",\n                        "reverted_card_payment?",\n                        "supported_cards_and_currencies",\n                        "terminate_account",\n                        "top_up_by_bank_transfer_charge",\n                        "top_up_by_card_charge",\n                        "top_up_by_cash_or_cheque",\n                        "top_up_failed",\n                        "top_up_limits",\n                        "top_up_reverted",\n                        "topping_up_by_card",\n                        "transaction_charged_twice",\n                        "transfer_fee_charged",\n                        "transfer_into_account",\n                        "transfer_not_received_by_recipient",\n                        "transfer_timing",\n                        "unable_to_verify_identity",\n                        "verify_my_identity",\n                        "verify_source_of_funds",\n                        "verify_top_up",\n                        "virtual_card_not_working",\n                        "visa_or_mastercard",\n                        "why_verify_identity",\n                        "wrong_amount_of_cash_received",\n                        "wrong_exchange_rate_for_cash_withdrawal",\n                    ]        \n',
  'batch_file': 'input_bank_batch.jsonl'}]

### API Calls

In [23]:
import os
import tiktoken

def split_file_by_token(input_file, max_tokens=2000, encoding_name="gpt2",
                        output_prefix="batch_part", output_extension=".jsonl"):
    """
    Splits an input file into multiple chunks such that each chunk does not exceed max_tokens.
    Tokens are counted using the specified encoding from the tiktoken library.
    
    Parameters:
      input_file (str): Path to the input file.
      max_tokens (int): Maximum number of tokens allowed per chunk.
      encoding_name (str): Name of the token encoding to use (default "gpt2").
      output_prefix (str): Prefix for the output file names.
      output_extension (str): Extension for the output files.
    
    Returns:
      List[str]: A list of created output file paths.
    """
    # Get the encoding for token counting.
    encoding = tiktoken.get_encoding(encoding_name)
    
    with open(input_file, "r", encoding="utf-8") as f:
        lines = f.readlines()
    
    chunks = []
    current_chunk = []
    current_tokens = 0
    all_tokens = 0
    
    # Process each line and accumulate tokens until the limit is reached.
    for line in lines:
        line_token_count = len(encoding.encode(line))
        if current_tokens + line_token_count > max_tokens and current_chunk:
            # If adding this line would exceed the limit, save the current chunk.
            chunks.append("".join(current_chunk))
            current_chunk = [line]
            current_tokens = line_token_count
        else:
            current_chunk.append(line)
            current_tokens += line_token_count
            
    if current_chunk:
        chunks.append("".join(current_chunk))
    
    output_files = []
    # Write each chunk to a separate output file.
    for idx, chunk in enumerate(chunks, start=1):
        output_filename = f"{output_prefix}{idx}{output_extension}"
        if os.path.exists(output_filename):
            print(f"The file '{output_filename}' already exists.")
            output_files.append(output_filename)
            continue
        with open(output_filename, "w", encoding="utf-8") as out_f:
            out_f.write(chunk)
        output_files.append(output_filename)
        token_count = len(encoding.encode(chunk))
        print(f"{output_filename}: {token_count} tokens")
        all_tokens += token_count
    
    print("\nDone! Created files:")
    for file in output_files:
        print(f" - {file}")
    print("Total tokens:")
    print(all_tokens)
    return output_files

In [24]:
# Upload batch file via File API
def upload_file(file, api_key):
    with open(file, "rb") as file_data:
        response = requests.post(
            "https://api.openai.com/v1/files",
            headers={"Authorization": f"Bearer {api_key}"},
            files={
                "file": ("batch_input.jsonl", file_data, "application/jsonl")
            },
            data={"purpose": "batch"}
        )
    print("\nUpload file:")
    print(file)
    print(response.json()['status'])
    return response.json()['id']

In [25]:
# Start batch processing
def start_batch(file_id, api_key):
    batch_payload = {
        "input_file_id": file_id,
        "endpoint": "/v1/chat/completions",
        "completion_window": "24h",  # only allowed value for 50% discount
    }
    response = requests.post(
        "https://api.openai.com/v1/batches",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        },
        json=batch_payload
    )
    batch_info = response.json()
    print("\nStart batch processing:")
    print(response.json()['status'])
    return response.json()['id']

In [26]:
# Batch processing status
def check_status(batch_id, api_key):
    check_status = requests.get(
        f"https://api.openai.com/v1/batches/{batch_id}",
        headers={"Authorization": f"Bearer {api_key}"}
    )
    print("\nCheck status:")
    print(check_status.json()['status'])
    print("Errors:")
    print(check_status.json()['errors'])
    return check_status.json()['output_file_id'], check_status.json()['status']

In [27]:
# Download the content of the output file
def download_processed_file(output_file_id, output_file, api_key):
    response = requests.get(
        f"https://api.openai.com/v1/files/{output_file_id}/content",
        headers={"Authorization": f"Bearer {api_key}"}
    )
    
    with open(output_file, "wb") as f:
        f.write(response.content)
    print("\nBatch results written to:")
    print(output_file)
    return output_file

### Run Batch API Workflow

In [28]:
api_key = "<key>"

In [29]:
def process_dataset(dataset, api_key):
    """
    Process one dataset: split the batch file into chunks, upload each chunk,
    start batch processing, check status (with retries) and finally download
    the processed file.
    """
    prefix = dataset['prefix']
    batch_file = dataset['batch_file']
    
    # Inform the user about the dataset
    print(f"\nProcessing dataset: {dataset['name']}")
    print(f"Description: {dataset['description']}")
    
    # Split the batch file into chunks (using max_tokens=1800000)
    output_prefix = f"{prefix}_batch_part"
    print("Splitting batch file...")
    chunk_files = split_file_by_token(
        input_file=batch_file,
        max_tokens=1800000,
        encoding_name="gpt2",
        output_prefix=output_prefix,
        output_extension=".jsonl"
    )
    
    # Process each chunk file
    for i, chunk in enumerate(chunk_files, start=1):
        output_file_name = f"{prefix}_output_chunk{i}.txt"
        if os.path.exists(output_file_name):
            print(f"The file '{output_file_name}' already exists.")
            continue
        print(f"\nProcessing chunk {i} of {len(chunk_files)}: {chunk}")
        file_id = upload_file(chunk, api_key)
        print(f"Uploaded file. Received file_id: {file_id}")
        
        max_retries = 24
        retry_count = 0
        batch_completed = False
        
        # Retry loop for starting the batch and checking its status
        while retry_count < max_retries and not batch_completed:
            batch_id = start_batch(file_id, api_key)
            print(f"Started batch. Received batch_id: {batch_id}")
            
            status_retry = 0
            while status_retry < max_retries:
                output_file_id, status = check_status(batch_id, api_key)
                print(f"Batch status: {status}")
                
                # If completed, break out of the inner loop
                if status.lower() == "completed":
                    batch_completed = True
                    break
                # If status indicates failure or cancellation, break to retry batch start
                elif status.lower() in ["failed", "cancelled"]:
                    print(f"Batch {batch_id} {status}. Retrying batch start in 1 hour...")
                    time.sleep(3600)  # Wait 1 hour
                    break
                else:
                    # Status is not completed (but not failed/cancelled): wait 1 hour and check again
                    print(f"Batch {batch_id} not completed yet. Checking again in 1 hour...")
                    time.sleep(3600)
                    status_retry += 1
            
            # If after inner loop batch is completed, proceed; otherwise, increment retry_count and retry start_batch
            if not batch_completed:
                retry_count += 1
                print(f"Retrying start_batch for chunk {i}. Attempt {retry_count}/{max_retries}...")
        
        if not batch_completed:
            print(f"Error: Maximum retries reached for chunk {i}. Aborting processing for dataset {dataset['name']}.")
            return False
        
        # Batch job completed: download the processed output file.
        downloaded_file = download_processed_file(output_file_id, output_file_name, api_key)
        print(f"Downloaded processed file: {downloaded_file}")
    
    return True

In [30]:
# List of dataset dictionaries to process
def run(datasets, api_key):
    overall_start = datetime.datetime.now()
    print("Process started at:", overall_start.strftime("%Y-%m-%d %H:%M:%S"))
    
    # Iterate over each dataset
    for dataset in datasets:
        dataset_start = datetime.datetime.now()
        print("\n============================")
        print(f"Starting processing for dataset: {dataset['name']}")
        print("Start time:", dataset_start.strftime("%Y-%m-%d %H:%M:%S"))
        
        success = process_dataset(dataset, api_key)
        if not success:
            print(f"Processing failed for dataset: {dataset['name']}. Aborting overall process.")
            return
        
        dataset_end = datetime.datetime.now()
        elapsed = dataset_end - dataset_start
        print(f"Finished processing dataset: {dataset['name']}")
        print("End time:", dataset_end.strftime("%Y-%m-%d %H:%M:%S"))
        print("Elapsed time for this dataset:", str(elapsed))
        print("============================\n")
    
    overall_end = datetime.datetime.now()
    total_elapsed = overall_end - overall_start
    print("All datasets processed.")
    print("Process ended at:", overall_end.strftime("%Y-%m-%d %H:%M:%S"))
    print("Total elapsed time:", str(total_elapsed))

In [ ]:
run(datasets, api_key)

Process started at: 2025-03-11 16:49:45

============================
Starting processing for dataset: BANKING77 dataset
Start time: 2025-03-11 16:49:45

Processing dataset: BANKING77 dataset
Description: BANKING77 dataset provides a very fine-grained set of intents in a banking domain. It comprises 13,083 customer service queries labeled with 77 intents. It focuses on fine-grained single-domain intent detection.
Splitting batch file...
The file 'bank77_batch_part1.jsonl' already exists.
The file 'bank77_batch_part2.jsonl' already exists.
The file 'bank77_batch_part3.jsonl' already exists.
The file 'bank77_batch_part4.jsonl' already exists.
The file 'bank77_batch_part5.jsonl' already exists.
The file 'bank77_batch_part6.jsonl' already exists.
The file 'bank77_batch_part7.jsonl' already exists.
The file 'bank77_batch_part8.jsonl' already exists.
The file 'bank77_batch_part9.jsonl' already exists.
The file 'bank77_batch_part10.jsonl' already exists.
The file 'bank77_batch_part11.jsonl' already exists.
The file 'bank77_batch_part12.jsonl' already exists.

Done! Created files:
 - bank77_batch_part1.jsonl
 - bank77_batch_part2.jsonl
 - bank77_batch_part3.jsonl
 - bank77_batch_part4.jsonl
 - bank77_batch_part5.jsonl
 - bank77_batch_part6.jsonl
 - bank77_batch_part7.jsonl
 - bank77_batch_part8.jsonl
 - bank77_batch_part9.jsonl
 - bank77_batch_part10.jsonl
 - bank77_batch_part11.jsonl
 - bank77_batch_part12.jsonl
Total tokens:
0
The file 'bank77_output_chunk1.txt' already exists.
The file 'bank77_output_chunk2.txt' already exists.
The file 'bank77_output_chunk3.txt' already exists.
The file 'bank77_output_chunk4.txt' already exists.
The file 'bank77_output_chunk5.txt' already exists.
The file 'bank77_output_chunk6.txt' already exists.
The file 'bank77_output_chunk7.txt' already exists.
The file 'bank77_output_chunk8.txt' already exists.
The file 'bank77_output_chunk9.txt' already exists.
The file 'bank77_output_chunk10.txt' already exists.
The file 'bank77_output_chunk11.txt' already exists.
The file 'bank77_output_chunk12.txt' already exists.
Finished processing dataset: BANKING77 dataset
End time: 2025-03-11 16:49:50
Elapsed time for this dataset: 0:00:05.632322
============================


============================
Starting processing for dataset: Hate Speech
Start time: 2025-03-11 16:49:50

Processing dataset: Hate Speech
Description: Dataset of hate speech annotated on Internet forum posts in English at sentence-level. The source forum in Stormfront, a large online community of white nacionalists. A total of 10,568 sentence have been been extracted from Stormfront and classified as conveying hate speech or not.
Splitting batch file...
The file 'hate_batch_part1.jsonl' already exists.
The file 'hate_batch_part2.jsonl' already exists.
The file 'hate_batch_part3.jsonl' already exists.
The file 'hate_batch_part4.jsonl' already exists.
The file 'hate_batch_part5.jsonl' already exists.
The file 'hate_batch_part6.jsonl' already exists.
The file 'hate_batch_part7.jsonl' already exists.
The file 'hate_batch_part8.jsonl' already exists.
The file 'hate_batch_part9.jsonl' already exists.
The file 'hate_batch_part10.jsonl' already exists.
The file 'hate_batch_part11.jsonl' already exists.

Done! Created files:
 - hate_batch_part1.jsonl
 - hate_batch_part2.jsonl
 - hate_batch_part3.jsonl
 - hate_batch_part4.jsonl
 - hate_batch_part5.jsonl
 - hate_batch_part6.jsonl
 - hate_batch_part7.jsonl
 - hate_batch_part8.jsonl
 - hate_batch_part9.jsonl
 - hate_batch_part10.jsonl
 - hate_batch_part11.jsonl
Total tokens:
0
The file 'hate_output_chunk1.txt' already exists.
The file 'hate_output_chunk2.txt' already exists.
The file 'hate_output_chunk3.txt' already exists.
The file 'hate_output_chunk4.txt' already exists.
The file 'hate_output_chunk5.txt' already exists.
The file 'hate_output_chunk6.txt' already exists.

Processing chunk 7 of 11: hate_batch_part7.jsonl

Upload file:
hate_batch_part7.jsonl
processed
Uploaded file. Received file_id: file-MZRDiB2H6HGESzBd994TCV

Start batch processing:
validating
Started batch. Received batch_id: batch_67d05ba5ffc48190a30caebe39f3457b

Check status:
validating
Errors:
None
Batch status: validating
Batch batch_67d05ba5ffc48190a30caebe39f3457b not completed yet. Checking again in 1 hour...